In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('Volcanoes_USA.csv')

In [6]:
data.loc[:,'LAT':'LON']

          LAT         LON
0   48.776798 -121.810997
1   48.111801 -121.111000
2   46.869801 -121.751000
3   46.199799 -122.181000
4   46.205799 -121.490997
5   45.879799 -122.081001
6   45.929798 -121.820999
7   45.373798 -121.691002
8   44.691799 -121.801002
9   44.419800 -121.771004
10  44.379799 -121.931000
11  44.331799 -121.831001
12  44.284802 -121.841003
13  44.169800 -121.771004
14  44.099800 -121.771004
15  43.978802 -121.681000
16  43.721802 -121.221001
17  43.569801 -121.820999
18  43.511902 -120.861000
19  43.240799 -122.100998
20  43.471901 -120.751000
21  43.360901 -120.661003
22  42.929901 -122.121002
23  44.429901 -110.670998
24  43.099899 -118.751000
25  43.149898 -117.471001
26  42.999901 -117.801002
27  43.419899 -113.501000
28  43.499901 -112.450996
29  43.179901 -114.350998
..        ...         ...
32  42.879902 -113.221001
33  41.419899 -122.200996
34  41.177898 -121.441002
35  40.954899 -121.361000
36  40.779900 -121.600998
37  40.679901 -121.551002
38  40.629902 -120.831001
39  40.491901 -121.501000
40  38.969898 -122.771004
41  39.374901 -119.721001
42  39.650002 -107.030998
43  37.999901 -119.030998
44  38.970001 -112.501000
45  37.879902 -119.001000
46  37.691898 -119.021004
47  37.699902 -118.871002
48  37.579899 -119.051002
49  37.019901 -117.450996
50  37.580002 -112.670998
51  37.257000 -113.621002
52  37.327999 -112.401001
53  36.357899 -118.320999
54  36.029900 -117.820999
55  36.380001 -113.130997
56  34.750000 -116.621002
57  35.869999 -106.570999
58  35.369999 -111.501000
59  34.549999 -115.780998
60  34.799999 -108.001000
61  33.780102 -105.931000

[62 rows x 2 columns]